name: CI CD

on: 
  workflow_dispatch: 
  push:
    branches:
      - 'main'
      - 'feature/*'

jobs:
  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repositoy
        uses: actions/checkout@v7
      
      - name: Setup NodeJs
        uses: actions/setup-node@v6

      - name: Install Dependencies
        run: npm install 

      - name: Unit test
        run: npm run test
      
      - name: Upload The Unit Test Report
        uses: actions/upload-artifact@v7
        with:
          name: unit_test_report
          path: junit-report.xml

  code_coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repositoy
        uses: actions/checkout@v7
      
      - name: Setup NodeJs
        uses: actions/setup-node@v6

      - name: Install Dependencies
        run: npm install 

      - name: Code coverage
        run: npm run coverage
      
      - name: Upload The Coverage Report
        uses: actions/upload-artifact@v7
        with:
          name: coverage_report
          path: coverage